version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: niviorganics
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    ports:
      - "3010:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/niviorganics?schema=public
      - NEXTAUTH_SECRET=supersecret123
      - NEXTAUTH_URL=http://localhost:3010
    depends_on:
      db:
        condition: service_healthy
    command: /bin/sh -c "npx prisma db push && npm run build && npm start"

volumes:
  postgres_data:
